# config/config.yaml

scale: 16
params:
  regime: 'forcing_no_t_dep'
  Lx: 6.283185307179586  # 2 * math.pi
  Ly: 6.283185307179586  # 2 * math.pi
  Nx: 128
  Ny: 128
  dt: 0.0016  # (1.0E-4) * scale
  mu: 0.02
  nu: 1.025E-5
  t0: 0.0
  nv: 1
  B: 0
  device: "cuda"
  topography: True
  seed: 20240605
  
qg_solver:
  solver: 'rk4'
  rtol: 1e-4
  atol: 1e-4
  step_size: 1.6e-3
  adjoint: True
  autonomous: False
  num_steps: 200
  
qg_data:
  path: '/homes/s23roy/project_QG/data/4dvar/stream_function_dataset_forcing_no_t_lr_128_dt=0.0002_save_freq=1600.nc'
  tgt: 'stream_function'
  sparsity: 5
  obs: 'sf_obs'
  state: 'vorticity'
  ob_masks: 'masks'

fourd_var:
  days: 10
  NIter: 500
  alpha_obs: 10.0
  alpha_dyn: 1.0
  delta: 0.1
  ic_type: 'blurred_ic'
  kernel_size: 21
  sigma: 8.0
  max_batch: 1
  gradient_smoothing: 'False'
  optimizer: 'SGD'
  
metric:
    rmse: 

hydra:
  run:
    dir: './outputs/trial_exps'
    
output:
  base_dir: "${hydra:runtime.output_dir}"
  dir_structure: "${output.base_dir}/${params.regime}_grid_${params.Nx}_ic_type_${fourd_var.ic_type}_with_smooth_gradient_${fourd_var.gradient_smoothing}/${fourd_var.optimizer}"
  losses_file: "${output.dir_structure}/losses.npy"
  solution_file: "${output.dir_structure}/optimal_4dvar_solution.npy"
